# Header
menu:
  Home: /
  zammu.in: https://zammu.in/
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- sidebar_head
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-72393916-1
favicon: /favicon.png
twitter: zammuhq
google_plus:
fb_admins:
fb_app_id:
